version: "3.7"

services:
  front:
    container_name: front
    image: front
    build: ./front
    volumes:
      - ./front:/Localib/front
    ports:
      - 3001:3000
    depends_on:
      - back
  back:
    container_name: back
    build: ./back
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo_db

  mobile:
    container_name: mobile
    image: mobile
    build: ./mobile
    volumes:
      - ./mobile:/Localib/mobile
    ports:
      - 3000:3000
    depends_on:
      - back

  mongo_db:
    container_name: db
    image: mongo
    restart: always
    ports:
      - 27017:27017
